name: First Workflow

on: 
  workflow_dispatch: 

jobs:
  create-branch:
    name: "Create Dynamic Branch"
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Name
        id: set-branch-name
        run: |
          branch_name="dynamic-branch-$(date +'%Y%m%d%H%M%S')"
          echo "::set-output name=branch_name::$branch_name"
       
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Create Branch
        run: |
          branch_name=${{  steps.set-branch-name.outputs.branch_name  }}
          git checkout -b $branch_name
          git push --set-upstream origin $branch_name
