name: First Workflow

on: 
  workflow_dispatch: 

jobs:
  create-branch:
    name: "Create Dynamic Branch"
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Name
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            branch: 'release-notes'
            sha: '${{ github.event.pull_request.head.sha }}'
