name: First Workflow

on: 
  workflow_dispatch: 

jobs:
  create-branch:
    name: "Create Dynamic Branch"
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Name
        id: set-branch-name
        run: |
          branch_name="dynamic-branch-$(date +'%Y%m%d%H%M%S')"
          echo "branch_name=$branch_name" >> $GITHUB_ENV
       
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git for GitHub Actions
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
  
        
      - name: Create and Push Branch
        run: |
          git checkout -b $branch_name
           echo "This is a new file created by GitHub Actions" > new-file.txt
          
          # Stage the new file
          git add new-file.txt
          
          # Commit the new file
          git commit -m "Add new-file.txt to $branch_name"

          # Push the new branch with the new file to GitHub
          git push --set-upstream origin "$branch_name"
        env:
          branch_name: ${{ env.branch_name }}

      - name: Run some tests or condition
        run: |
          echo "Running tests"
          # Simulate a test or condition
          if [[ ${{ steps.set-branch-name.conclusion }} == 'success' ]]; then
            echo "Condition met"
          else
            echo "Condition not met"
            exit 1
          fi
      - name: Trigger Workflow 2 if condition is met
        if: success()  # This step triggers Workflow 2 only if Workflow 1 succeeded
        run: |
         curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "trigger-workflow-2"}'