name: workflow path based test

on: 
  push: 
    branches: [staging]

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.changes }}
      frontend: ${{ steps.filter.outputs.changes }}
    steps:
    # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  # JOB to build and test backend code
  backend:    

    outputs:
        pr: ${{ steps }}
    needs: changes
    if: ${{ needs.changes.outputs.backend == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
            base: main\
      - name: Create Pull Request for Backend Changes
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update backend"
          title: "Backend updates from staging"
          body: "This PR includes recent changes in the backend from the staging branch."
          branch: backend-changes-staging
          base: main


  # JOB to build and test frontend code
  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Create Pull Request for Frontend Changes
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update frontend"
          title: "Frontend updates from staging"
          body: "This PR includes recent changes in the frontend from the staging branch."
          branch: frontend-changes-staging
          base: main
