name: workflow path based test

on: 
  push

jobs:
  # Job to detect changes in backend and frontend directories
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Paths filter to detect changes in backend and frontend directories
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'       # Match files in backend directory
            frontend:
              - 'frontend/**'      # Match files in frontend directory

      - name: List uncommitted changes
        run: git status --untracked-files=all --short          

      # Debugging: Print the values of backend and frontend change detection
      - name: Debug Outputs
        run: |
          echo "Backend changes detected: ${{ steps.filter.outputs.backend }}"
          echo "Frontend changes detected: ${{ steps.filter.outputs.frontend }}"

  # Job to build and test backend code if backend changes are detected
  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # Debugging: Confirm backend job is running due to detected changes
      - name: Backend Debug
        run: echo "Running backend job because changes were detected in backend/ directory."

  # Job to build and test frontend code if frontend changes are detected
  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Debugging: Confirm frontend job is running due to detected changes
      - name: Frontend Debug
        run: echo "Running frontend job because changes were detected in frontend/ directory."
