name: Workflow 2

on:
  workflow_run:
    workflows: ["First Workflow"]  # This should match the name of the first workflow
    types:
      - completed

jobs:
  follow_up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run some follow-up action
        run: |
          echo "Workflow 1 completed successfully, running Workflow 2."
